### PR TITLE
Fix for issue #2.

### PR DESCRIPTION
**Pull request by dschiera95**

### CODE REVIEW

**Comment by mohamdio** [comment]
Thanks for fixing this issue 👍

**Comment by dschiera95** [comment]
Awesome! Thanks for merging.
I am finding this library very useful.
I use composer to install this, can you bump the version, or is that something I can do, and then submit another Pull request for?

**Comment by mohamdio** [comment]
Thank you, feel free to update it for sure and I will merge your new pull request.
---
Sorry for the delay.

**Comment by dschiera95** [comment]
It's been a while, but I'm still using this library and it's working out great.
I just realized that I cannot bump the version myself with a pull commit.
Would you mind created a new tag/release? Something like 1.0.1?
Thanks!

**Comment by mohamdio** [comment]
Really, I don't have time to maintain this module, so I will add you as a collaborator, so you can do any changes to make this module working fine for others.

**Pull request merged**
